# General training loop config
run_name: &run_name 'breakout-rainbow'
train_steps: 10000000
test_frequency: 100
test_num_episodes: 10
saving_schedule:
  name: 'PeriodicSchedule'
  kwargs:
    off_value: False
    on_value: True
    period: 15000
save_dir: 'experiment'

# Environment config
environment:
  name: 'MinAtarEnv'
  kwargs:
    env_name: 'breakout'

# List of agents for the experiment. In single agent, only the first agent in
# the list is used.
agent:
  name: 'RainbowDQNAgent'
  kwargs:
    qnet:
      name: 'DistributionalConv'
      kwargs:
        channels: [16]
        mlp_layers: [128]
        kernel_sizes: [3]
        strides: [1]
        paddings: [0]
        normalization_factor: 1
        noisy: True
        dueling: True
    optimizer_fn:
      name: 'RMSprop'
      kwargs:
        lr: 0.00025
        alpha: 0.95
        eps: 0.01
        centered: True
    id: 0
    replay_buffer:
      name: 'EfficientCircularBuffer'
      kwargs:
        seed: 43
        capacity: 100000
        stack_size: 1
    discount_rate: .99
    target_net_update_schedule:
      name: 'PeriodicSchedule'
      kwargs:
        off_value: False
        on_value: True
        period: 1000
    epsilon_schedule:
      name: 'LinearSchedule'
      kwargs:
        init_value: 1
        end_value: 0.1
        steps: 100000
    learn_schedule:
      name: 'SwitchSchedule'
      kwargs:
        off_value: False
        on_value: True
        steps: 5000
    seed: 43
    batch_size: 32
    device: 'cpu'
    log_frequency: 1000
    double: True
    distributional: True
    use_eps_greedy: False
    v_min: 0.0
    v_max: 200.0
    atoms: 51

# List of logger configs used.
loggers:
  -
    name: ChompLogger
    kwargs: {}
  -
    name: WandbLogger
    kwargs:
      project_name: Hive-v1
      run_name: *run_name
      mode: "online"
