# General training loop config
run_name: &run_name 'cartpole-random'
train_steps: 30000
test_frequency: 10
test_num_episodes: 1
saving_schedule:
  name: 'PeriodicSchedule'
  kwargs:
    off_value: False
    on_value: True
    period: 15000
save_dir: 'experiment'

# Environment config
environment:
  name: 'GymEnv'
  kwargs:
    env_name: 'CartPole-v0'

# List of agents for the experiment. In single agent, only the first agent in
# the list is used.
agents: 
  - 
    name: 'RandomAgent'
    kwargs:
      id: 0
      seed: 42
      device: 'cpu'
      log_frequency: 100

# List of logger configs used.
loggers:
  -
    name: ChompLogger
    kwargs: {}
  -
    name: WandbLogger
    kwargs:
      project_name: Hive-v1
      run_name: *run_name
      offline: False
