# General training loop config
run_name: &run_name 'breakout-dqn'
train_steps: 10000000
test_frequency: 100
test_num_episodes: 10
saving_schedule:
  name: 'PeriodicSchedule'
  kwargs:
    off_value: False
    on_value: True
    period: 15000
save_dir: 'experiment'

# Environment config
environment:
  name: 'MinAtarEnv'
  kwargs:
    env_name: 'breakout-v0'

# List of agents for the experiment. In single agent, only the first agent in
# the list is used.
agent:
  name: 'DQNAgent'
  kwargs:
    qnet:
      name: 'MinAtarDQNModel'
    optimizer_fn:
      name: 'Adam'
      kwargs: {}
    id: 0
    replay_buffer:
      name: 'EfficientCircularBuffer'
      kwargs:
        seed: 42
        capacity: 1000000
        stack_size: 4
    discount_rate: .99
    target_net_update_schedule:
      name: 'PeriodicSchedule'
      kwargs:
        off_value: False
        on_value: True
        period: 10000
    epsilon_schedule:
      name: 'LinearSchedule'
      kwargs:
        init_value: 1
        end_value: 0.05
        steps: 1000000
    learn_schedule:
      name: 'SwitchSchedule'
      kwargs:
        off_value: False
        on_value: True
        steps: 500
    seed: 42
    batch_size: 32
    device: 'cuda'
    log_frequency: 1000

# List of logger configs used.
loggers:
  -
    name: ChompLogger
    kwargs: {}
  -
    name: WandbLogger
    kwargs:
      project_name: Hive-v1
      run_name: *run_name
      offline: False