# General training loop config
run_name: &run_name 'pursuit-rainbow'
train_steps: 30000
test_frequency: 10
test_num_episodes: 1
self_play: False
num_agents: 3
stack_size: &stack_size 2
saving_schedule:
  name: 'PeriodicSchedule'
  kwargs:
    off_value: False
    on_value: True
    period: 15000
save_dir: 'experiment'

# Environment config
environment:
  name: 'MarlGridEnv'
  kwargs:
    env_name: 'MarlGrid-2Agent1RandomPursuit8x8-v0'
    num_players: 2

# List of agents for the experiment. In single agent, only the first agent in
# the list is used.
agents:
  -
    name: 'RainbowDQNAgent'
    kwargs:
      qnet:
        name: 'DistributionalConv'
        kwargs:
          channels: [ 32, 64, 64 ]
          mlp_layers: [ 128, 128 ]
          kernel_sizes: [ 8, 4, 3 ]
          strides: [ 4, 2, 1 ]
          paddings: [ 0, 1, 1 ]
          noisy: True
          dueling: True
          sigma_init: 0.5
      optimizer_fn:
        name: 'Adam'
        kwargs:
          lr: 0.00025
          eps: 0.0003125
      id: 0
      replay_buffer:
        name: 'PrioritizedReplayBuffer'
        kwargs:
          seed: 42
          capacity: 100000
          stack_size: *stack_size
      discount_rate: .99
      target_net_update_schedule:
        name: 'PeriodicSchedule'
        kwargs:
          off_value: False
          on_value: True
          period: 1000
      epsilon_schedule:
        name: 'LinearSchedule'
        kwargs:
          init_value: 1
          end_value: 0.1
          steps: 100000
      learn_schedule:
        name: 'SwitchSchedule'
        kwargs:
          off_value: False
          on_value: True
          steps: 5000
      seed: 42
      batch_size: 32
      device: 'cpu'
      log_frequency: 1000
      double: True
      distributional: True
      use_eps_greedy: False
      v_min: 0
      v_max: 10.0
      atoms: 51
  -
    name: 'RainbowDQNAgent'
    kwargs:
      qnet:
        name: 'DistributionalConv'
        kwargs:
          channels: [ 32, 64, 64 ]
          mlp_layers: [ 128, 128 ]
          kernel_sizes: [ 8, 4, 3 ]
          strides: [ 4, 2, 1 ]
          paddings: [ 0, 1, 1 ]
          noisy: True
          dueling: True
          sigma_init: 0.5
      optimizer_fn:
        name: 'Adam'
        kwargs:
          lr: 0.00025
          eps: 0.0003125
      id: 1
      replay_buffer:
        name: 'PrioritizedReplayBuffer'
        kwargs:
          seed: 43
          capacity: 100000
          stack_size: *stack_size
      discount_rate: .99
      target_net_update_schedule:
        name: 'PeriodicSchedule'
        kwargs:
          off_value: False
          on_value: True
          period: 1000
      epsilon_schedule:
        name: 'LinearSchedule'
        kwargs:
          init_value: 1
          end_value: 0.1
          steps: 100000
      learn_schedule:
        name: 'SwitchSchedule'
        kwargs:
          off_value: False
          on_value: True
          steps: 5000
      seed: 43
      batch_size: 32
      device: 'cpu'
      log_frequency: 1000
      double: True
      distributional: True
      use_eps_greedy: False
      v_min: 0
      v_max: 10.0
      atoms: 51

# List of logger configs used.
loggers:
  -
    name: ChompLogger
    kwargs: {}
  -
    name: WandbLogger
    kwargs:
      project_name: Hive-v1
      run_name: *run_name
      mode: "online"
