# General training loop config
run_name: &run_name 'breakout-rainbow-double-dueling-dist'
train_steps: 10000000
test_frequency: 100
test_num_episodes: 10
saving_schedule:
  name: 'PeriodicSchedule'
  kwargs:
    off_value: False
    on_value: True
    period: 15000
save_dir: 'experiment'

# Environment config
environment:
  name: 'MinAtarEnv'
  kwargs:
    env_name: 'breakout'

# List of agents for the experiment. In single agent, only the first agent in
# the list is used.
agent:
  name: 'RainbowDQNAgent'
  kwargs:
    qnet:
      name: 'DistributionalMLP'
      kwargs:
        noisy: False
        dueling: True
        hidden_units: 256
        num_hidden_layers: 2
        sigma_init: 0.5
    optimizer_fn:
      name: 'Adam'
      kwargs:
        lr: 0.0001
#        alpha: 0.95
        eps: 0.0003125
#        centered: True
    id: 0
    replay_buffer:
      name: 'PrioritizedReplayBuffer'
      kwargs:
        seed: 43
        capacity: 100000
        stack_size: 1
    discount_rate: .99
    target_net_update_schedule:
      name: 'PeriodicSchedule'
      kwargs:
        off_value: False
        on_value: True
        period: 1000
    epsilon_schedule:
      name: 'LinearSchedule'
      kwargs:
        init_value: 1
        end_value: 0.1
        steps: 100000
    learn_schedule:
      name: 'SwitchSchedule'
      kwargs:
        off_value: False
        on_value: True
        steps: 5000
    seed: 43
    batch_size: 32
    device: 'cpu'
    log_frequency: 1000
    double: True
    distributional: True
    use_eps_greedy: True
    v_min: -100.0
    v_max: 100.0
    atoms: 51

# List of logger configs used.
loggers:
  -
    name: ChompLogger
    kwargs: {}
  -
    name: WandbLogger
    kwargs:
      project_name: Hive-v1
      run_name: *run_name
      mode: "online"
